print ("Enter Details User 1")
name_1 = input ("Enter Your Name: ")
password = input ("Enter User Password: ")
age_1 = int(input ("Enter Your Age: "))
print ("__________________________________")
print ("Enter Details User 2")
name_2 = input ("Enter Your Name: ")
password = input ("Enter User Password: ") 
age_2 = int(input ("Enter Your Age: "))
print ("__________________________________")
number_list = [age_1,age_2]
avg = sum(number_list)/len(number_list)
print ('Users: {} and {}'.format(name_1,name_2))
print('Total Age: ',age_1+age_2)
print('Average Age: ',avg,2)